### PR TITLE
Add flag to not emit metric by accounts and flag to push accounts to messenger without caching

### PR DESCRIPTION
**Pull request by vovkman**
Add flag to not emit metric by accounts and flag to push accounts to messenger without caching

### CODE REVIEW

**Review by NicolasPennie — APPROVED** [review]

**Comment by linuskendall** [comment]
This cache accounts by slot param though does it really make sense?

The issue is that it conflicts with the commitment level setting - so instead of adding a flag couldn't you just check if config.commitment_level == processed and in that case ignore the cache.

**Review by linuskendall — CHANGES_REQUESTED** [review]
I think the cache by slot setting need to take into account commitment level. I would remove this new param and instead have the same behaviour if commitment level is set to processed.

**Comment by vovkman** [comment]
> I think the cache by slot setting need to take into account commitment level. I would remove this new param and instead have the same behaviour if commitment level is set to processed.

This makes sense to me, it just changes behavior from current state processed where it will flatten account updates per slot. If we are okay with that then I will make the change

**Comment by linuskendall** [comment]
Yeah if commitment level is set to processed it seems logical to me to push account updates as soon as they are seen.

**Comment by danenbm** [comment]
I think this PR is too old now.  Feel free to reopen it if you are still interested in this behavior!  Thank you for your contributions in general!

**Pull request closed without merging**
